const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const scenes = JSON.parse(sessionStorage.getItem('td_scenes') || '[]');
let extraClips = JSON.parse(sessionStorage.getItem('td_extra') || '[]');
let plan = null;
const invalidatePlan = () => { plan=null; $('editResult').classList.add('hidden'); };
const save = () => { sessionStorage.setItem('td_scenes', JSON.stringify(scenes.map(({image,...scene}) => scene))); sessionStorage.setItem('td_extra', JSON.stringify(extraClips)); };
const clips = () => [...scenes.filter(s => s.clip).map(s => ({...s.clip, name:`장면 ${scenes.indexOf(s)+1}`,prompt:s.prompt})), ...extraClips];
const note = (message,error=false) => { $('globalStatus').textContent=message; $('globalStatus').classList.toggle('error',error); };
async function post(path,data,raw=false){const response=await fetch(path,{method:'POST',headers:raw?{}:{'Content-Type':'application/json'},body:raw?data:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error || '요청 실패');return result;}
function draw(){
  $('sceneList').innerHTML=scenes.map((s,i)=>`<article class="scene" data-id="${s.id}"><div class="scene-no">${String(i+1).padStart(2,'0')}</div><label class="photo">${s.image?`<img src="${s.image}" alt="장면 ${i+1} 시작 사진">`:'<span>＋</span><b>시작 사진 넣기</b><small>JPG · PNG · WEBP</small>'}<input class="scene-image" type="file" accept="image/jpeg,image/png,image/webp"></label><div class="scene-fields"><label>MiniMax H3 공식 양식 프롬프트<textarea class="scene-prompt" placeholder="준비된 H3 프롬프트를 그대로 붙여넣으세요">${esc(s.prompt)}</textarea></label><p>프롬프트는 외부에서 준비한 내용을 그대로 사용합니다.</p></div><div class="scene-actions"><label>영상 길이<select class="scene-duration">${[4,5,6,7,8,9,10,11,12,13,14,15].map(n=>`<option value="${n}" ${s.duration===n?'selected':''}>${n}초</option>`).join('')}</select></label><button class="primary scene-generate" ${s.busy?'disabled':''}>${s.clip?'다시 만들기':s.taskId?'상태 다시 확인':'영상 만들기'}</button><span class="scene-state ${s.error?'error':''}">${esc(s.status || '사진과 프롬프트를 넣어 주세요.')}${s.taskId && !s.clip?`<br>작업 ID ${esc(s.taskId)}`:''}</span><button class="remove" title="이 장면 삭제">장면 삭제</button></div></article>`).join('');
  const all=clips();$('clipList').innerHTML=all.length?all.map((clip,i)=>`<div class="clip"><video src="${clip.url}#t=0.2" controls preload="metadata"></video><div><b>${i+1}. ${esc(clip.name)}</b><small>${Number(clip.duration).toFixed(1)}초</small></div></div>`).join(''):'<div class="empty">완성된 영상이 여기에 순서대로 모입니다.</div>';
  $('exportVideo').disabled=!all.length;
}
function sceneOf(element){return scenes.find(s=>s.id===element.closest('.scene')?.dataset.id);}
$('addScene').onclick=()=>{scenes.push({id:crypto.randomUUID(),prompt:'',duration:5,status:''});save();draw();};
$('sceneList').oninput=event=>{const s=sceneOf(event.target);if(!s)return;if(event.target.matches('.scene-prompt'))s.prompt=event.target.value;if(event.target.matches('.scene-duration'))s.duration=Number(event.target.value);save();};
$('sceneList').onchange=event=>{if(!event.target.matches('.scene-image'))return;const s=sceneOf(event.target),file=event.target.files[0];if(!file)return;if(file.size>30*1024*1024){s.status='사진은 30MB 이하여야 합니다.';s.error=true;draw();return;}const reader=new FileReader();reader.onload=()=>{s.image=reader.result;s.status='사진 준비 완료';s.error=false;draw();};reader.readAsDataURL(file);};
$('sceneList').onclick=event=>{const s=sceneOf(event.target);if(!s)return;if(event.target.matches('.remove')){scenes.splice(scenes.indexOf(s),1);invalidatePlan();save();draw();return;}if(event.target.matches('.scene-generate'))generate(s);};
function refreshScene(s,message,error=false){s.status=message;s.error=error;save();draw();}
async function generate(s){const key=$('minimaxKey').value.trim();if(!key)return refreshScene(s,'API 키 설정에서 MiniMax 키를 입력하세요.',true);if(s.clip&&(!s.image||!s.prompt.trim()))return refreshScene(s,'다시 만들려면 시작 사진과 프롬프트를 확인하세요.',true);if(s.clip){s.clip=null;s.taskId=null;invalidatePlan();}if(!s.taskId&&(!s.image||!s.prompt.trim()))return refreshScene(s,'시작 사진과 H3 프롬프트를 모두 넣으세요.',true);s.busy=true;refreshScene(s,s.taskId?'생성 상태 확인 중…':'MiniMax H3에 영상 생성 요청 중…');try{if(!s.taskId){const result=await post('/api/h3/generate',{key,prompt:s.prompt,image:s.image,duration:s.duration});s.taskId=result.taskId;refreshScene(s,'생성 중…');}await poll(s);}catch(error){refreshScene(s,error.message,true);}finally{s.busy=false;draw();}}
async function poll(s){let wait=5000;while(s.taskId&&!s.clip&&scenes.includes(s)){await new Promise(resolve=>setTimeout(resolve,wait));let result;try{result=await post('/api/h3/status',{key:$('minimaxKey').value.trim(),taskId:s.taskId});wait=5000;}catch(error){refreshScene(s,`상태 확인 대기: ${error.message}`,true);wait=Math.min(wait*2,60000);continue;}if(result.status==='succeeded'){s.clip=result.clip;invalidatePlan();refreshScene(s,'영상 완성! 아래 목록에 자동 추가됐습니다.');note('완성 영상이 추가되었습니다. ChatGPT 편집을 진행할 수 있습니다.');return;}if(['failed','cancelled'].includes(result.status)){s.taskId=null;refreshScene(s,`생성 실패: ${result.error||result.status}`,true);return;}refreshScene(s,result.status==='running'?'영상 생성 중…':'생성 대기 중…');}}
$('extraVideos').onchange=async event=>{for(const file of event.target.files){if(!file.type.startsWith('video/'))continue;note(`${file.name} 가져오는 중…`);try{const result=await post('/api/upload',file,true);extraClips.push({...result,name:file.name,prompt:''});invalidatePlan();save();draw();}catch(error){note(error.message,true);}}note('기존 영상이 추가되었습니다.');};
$('aiEdit').onclick=async()=>{const all=clips(),key=$('openaiKey').value.trim(),instruction=$('editInstruction').value.trim();if(!all.length||!key||!instruction)return note('완성 영상, OpenAI API 키, 편집 지시를 입력하세요.',true);$('aiEdit').disabled=true;note('ChatGPT가 완성 영상을 보고 편집안을 만드는 중…');try{plan=await post('/api/ai/edit',{key,instruction,clips:all});const names=Object.fromEntries(all.map(c=>[c.id,c.name]));$('editResult').classList.remove('hidden');$('editResult').innerHTML=`<p>${esc(plan.summary)}</p><ol>${plan.clips.map(c=>`<li>${esc(names[c.id]||c.id)} · ${Number(c.start).toFixed(1)}–${Number(c.end).toFixed(1)}초</li>`).join('')}</ol><p>음소거 ${plan.mutes.length}구간 · 아래 버튼으로 이 편집안을 MP4로 만듭니다.</p>`;note('편집안이 적용되었습니다. MP4를 내려받을 수 있습니다.');}catch(error){note(`ChatGPT 편집 실패: ${error.message}`,true);}finally{$('aiEdit').disabled=false;}};
$('exportVideo').onclick=async()=>{const all=clips();if(!all.length)return;const selected=plan?plan.clips:all.map(c=>({id:c.id,start:0,end:c.duration}));$('exportVideo').disabled=true;note('최종 MP4를 만드는 중…');try{const result=await post('/api/export',{clips:selected,mutes:plan?.mutes||[],speech:[]});const link=document.createElement('a');link.href=result.url;link.download='taeyoon-doyoon-final.mp4';link.click();note('최종 MP4가 준비되었습니다.');}catch(error){note(`내보내기 실패: ${error.message}`,true);}finally{$('exportVideo').disabled=false;}};
if(!scenes.length)scenes.push({id:crypto.randomUUID(),prompt:'',duration:5,status:''});draw();
